/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RafflesIdRouteImport } from './routes/raffles.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardSellerRouteImport } from './routes/_authenticated/dashboard.seller'
import { Route as AuthenticatedDashboardBuyerRouteImport } from './routes/_authenticated/dashboard.buyer'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardSellerNewRouteImport } from './routes/_authenticated/dashboard.seller.new'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RafflesIdRoute = RafflesIdRouteImport.update({
  id: '/raffles/$id',
  path: '/raffles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardSellerRoute =
  AuthenticatedDashboardSellerRouteImport.update({
    id: '/seller',
    path: '/seller',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBuyerRoute =
  AuthenticatedDashboardBuyerRouteImport.update({
    id: '/buyer',
    path: '/buyer',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSellerNewRoute =
  AuthenticatedDashboardSellerNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardSellerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/fairness': typeof FairnessRoute
  '/legal': typeof LegalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/raffles/$id': typeof RafflesIdRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/dashboard/seller': typeof AuthenticatedDashboardSellerRouteWithChildren
  '/dashboard/seller/new': typeof AuthenticatedDashboardSellerNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/fairness': typeof FairnessRoute
  '/legal': typeof LegalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/raffles/$id': typeof RafflesIdRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/dashboard/seller': typeof AuthenticatedDashboardSellerRouteWithChildren
  '/dashboard/seller/new': typeof AuthenticatedDashboardSellerNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/fairness': typeof FairnessRoute
  '/legal': typeof LegalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/raffles/$id': typeof RafflesIdRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/_authenticated/dashboard/seller': typeof AuthenticatedDashboardSellerRouteWithChildren
  '/_authenticated/dashboard/seller/new': typeof AuthenticatedDashboardSellerNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/fairness'
    | '/legal'
    | '/sitemap.xml'
    | '/dashboard'
    | '/raffles/$id'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/dashboard/seller/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/fairness'
    | '/legal'
    | '/sitemap.xml'
    | '/dashboard'
    | '/raffles/$id'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/dashboard/seller/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/fairness'
    | '/legal'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/raffles/$id'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/buyer'
    | '/_authenticated/dashboard/seller'
    | '/_authenticated/dashboard/seller/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  FairnessRoute: typeof FairnessRoute
  LegalRoute: typeof LegalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RafflesIdRoute: typeof RafflesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffles/$id': {
      id: '/raffles/$id'
      path: '/raffles/$id'
      fullPath: '/raffles/$id'
      preLoaderRoute: typeof RafflesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/seller': {
      id: '/_authenticated/dashboard/seller'
      path: '/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof AuthenticatedDashboardSellerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/buyer': {
      id: '/_authenticated/dashboard/buyer'
      path: '/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof AuthenticatedDashboardBuyerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/seller/new': {
      id: '/_authenticated/dashboard/seller/new'
      path: '/new'
      fullPath: '/dashboard/seller/new'
      preLoaderRoute: typeof AuthenticatedDashboardSellerNewRouteImport
      parentRoute: typeof AuthenticatedDashboardSellerRoute
    }
  }
}

interface AuthenticatedDashboardSellerRouteChildren {
  AuthenticatedDashboardSellerNewRoute: typeof AuthenticatedDashboardSellerNewRoute
}

const AuthenticatedDashboardSellerRouteChildren: AuthenticatedDashboardSellerRouteChildren =
  {
    AuthenticatedDashboardSellerNewRoute: AuthenticatedDashboardSellerNewRoute,
  }

const AuthenticatedDashboardSellerRouteWithChildren =
  AuthenticatedDashboardSellerRoute._addFileChildren(
    AuthenticatedDashboardSellerRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardBuyerRoute: typeof AuthenticatedDashboardBuyerRoute
  AuthenticatedDashboardSellerRoute: typeof AuthenticatedDashboardSellerRouteWithChildren
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardBuyerRoute: AuthenticatedDashboardBuyerRoute,
    AuthenticatedDashboardSellerRoute:
      AuthenticatedDashboardSellerRouteWithChildren,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  FairnessRoute: FairnessRoute,
  LegalRoute: LegalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RafflesIdRoute: RafflesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
